#!/bin/bash

set -e

case "${1}" in
    triggered)
        for trigger in ${2}; do
            case "${trigger}" in

                /etc/xdg/xfce4/xinitrc)
                    debug "Setting XFCE Qubes App Menus..."
                    sed -i 's|XDG_MENU_PREFIX="xfce-"|XDG_MENU_PREFIX="xfce-qubes-"|g' /etc/xdg/xfce4/xinitrc
                    ;;

            esac
        done
        exit 0
        ;;

    *)
        echo "postinst called with unknown argument \`${1}'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0

# vim: set ts=4 sw=4 sts=4 et :
